kind: Service
apiVersion: v1
metadata:
  name: authors
  labels:
    app: authors
spec:
  type: NodePort
  ports:
    - port: 3000  
      protocol: TCP
      name: http
  selector:
    app: authors
---
