    - job_name: 'webapi'
      scheme: 'http'
      tls_config:
        insecure_skip_verify: true
      kubernetes_sd_configs:
      - role: endpoints
      relabel_configs:
      - source_labels: [__meta_kubernetes_service_annotation_webapi]
        action: keep
        regex: true
kind: ConfigMap
